name: ci NuGet

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-restore --configuration Release 

  generate-version:
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Tag Bump
        id: tab_bump
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: patch

    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  package-and-publish-lib:
    runs-on: ubuntu-latest
    needs: generate-version

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Generate NuGet package
        run: |
          dotnet pack \
          --configuration Release \
          -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
          -p:RepositoryUrl=https://github.com/p-bieber/Core-ValueObjects \
          -o packages

      - name: Publish NuGet package on GitHub
        run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.PUSH_NUGET_GIT }} --source https://nuget.pkg.github.com/p-bieber/index.json

      - name: Publish NuGet package on Nuget.org
        run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.PUSH_NUGET_ORG }} --source https://api.nuget.org/v3/index.json
